# Generated by Django 5.2.7 on 2025-10-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('editorial', models.CharField(max_length=100)),
                ('año_publicacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Cantidad total de este libro')),
                ('disponibles', models.PositiveIntegerField(blank=True, help_text='Cantidad disponible para prestar')),
            ],
        ),
    ]
