# Generated by Django 5.2.7 on 2025-10-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_prevista', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido')], default='activo', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
